In [1]:
import numpy as np

### Creating of array

In [141]:
a = [1,2,3,4,5]
arr = np.array(a)

In [142]:
print(arr)

[1 2 3 4 5]


In [12]:
arr.shape

(5,)

### 2D Array

In [143]:
arr1 = np.array([ [1,2], [3,4], [5,6] ])
print(arr1)

[[1 2]
 [3 4]
 [5 6]]


In [144]:
arr1.shape

(3, 2)

### 3D  array

In [22]:
arr2 = np.array([[[1,2,3], [3,4,5]],
                 [[1,2,6], [3,4,7]]])

In [23]:
print(arr2)

[[[1 2 3]
  [3 4 5]]

 [[1 2 6]
  [3 4 7]]]


In [21]:
arr2.shape

(2, 2, 3)

### Array filled with Zeroes

In [148]:
arr1 = np.zeros(shape=(3,3), dtype=int)
print(arr1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Array filled with Ones

In [151]:
arr1 = np.ones(shape=(3,2,4), dtype=int)
print(arr1)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


### Array with specific number .full()

In [150]:
arr = np.full((3,3), 10)
print(arr)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


### Identity Matrix: .eye()

In [157]:
arr = np.eye(3, dtype=int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Linspace matrix withing range

In [165]:
np.linspace(1, 99, 12, dtype=int)

array([ 1,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [35]:
np.linspace(0, 1, 10, dtype=float)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [42]:
np.linspace(1, 1000, 10, dtype=int)

array([   1,  112,  223,  334,  445,  556,  667,  778,  889, 1000])

### Indexing and Accessing

In [43]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [44]:
arr[0]

1

In [45]:
arr[1:4]        # arr[start: stop : step]

array([2, 3, 4])

In [46]:
arr[:4:2]

array([1, 3])

In [47]:
arr[-2:]

array([4, 5])

In [48]:
arr = np.full((3,3), 12)

In [49]:
arr

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [50]:
arr[0][1:]

array([12, 12])

In [166]:
arr = np.array([[1, 2, 3],
       [12, 13, 14],
       [4, 5,6]])
arr

array([[ 1,  2,  3],
       [12, 13, 14],
       [ 4,  5,  6]])

In [171]:
arr[1][:2]

array([[1, 2, 3]])

In [57]:
arr[::2][::2]

array([[1, 2, 3]])

In [65]:
arr[:2][:1]

array([[1, 2, 3]])

In [68]:
arr = np.linspace(1, 20, 10)
arr

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [69]:
arr[-5:]

array([11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [72]:
arr[-5]

11.555555555555555

### Slicing of 2D arrays

In [80]:
arr = np.array([[1, 2, 3],
       [12, 13, 14],
       [4, 5,6]])
arr

array([[ 1,  2,  3],
       [12, 13, 14],
       [ 4,  5,  6]])

In [74]:
arr[1]

array([12, 13, 14])

In [75]:
arr[1][:1]

array([12])

In [84]:
arr[1:, 2]

array([14,  6])

In [83]:
arr[:,:]

array([[ 1,  2,  3],
       [12, 13, 14],
       [ 4,  5,  6]])

In [82]:
arr[:,1]

array([ 2, 13,  5])

In [81]:
arr[1:,1]

array([13,  5])

In [85]:
arr

array([[ 1,  2,  3],
       [12, 13, 14],
       [ 4,  5,  6]])

In [86]:
arr[1,1]

13

In [87]:
arr[1:]

array([[12, 13, 14],
       [ 4,  5,  6]])

In [88]:
arr[1:, :]

array([[12, 13, 14],
       [ 4,  5,  6]])

In [89]:
arr[1:, 1:]

array([[13, 14],
       [ 5,  6]])

In [90]:
arr[,1]

SyntaxError: invalid syntax (2468986438.py, line 1)

In [91]:
arr[:, 1]

array([ 2, 13,  5])

In [93]:
arr[::2,1:]

array([[2, 3],
       [5, 6]])

In [94]:
id(arr)

4413991088

### Array Assignment

In [95]:
a1 = arr

In [96]:
id(a1)

4413991088

In [97]:
a1

array([[ 1,  2,  3],
       [12, 13, 14],
       [ 4,  5,  6]])

In [98]:
a1 = arr.copy()
id(a1)

4414314448

In [109]:
a1 = arr.__deepcopy__
id(a1)

4414236496

### Matrix Methods

In [100]:
a1

<function ndarray.__deepcopy__>

In [101]:
print(a1)

<built-in method __deepcopy__ of numpy.ndarray object at 0x1071828b0>


array(<built-in method __deepcopy__ of numpy.ndarray object at 0x1071828b0>,
      dtype=object)

In [112]:
a1 = arr.copy()

In [104]:
a1

array([[ 1,  2,  3],
       [12, 13, 14],
       [ 4,  5,  6]])

In [105]:
arr

array([[ 1,  2,  3],
       [12, 13, 14],
       [ 4,  5,  6]])

#### Add methods

In [106]:
np.add(a1,arr)

array([[ 2,  4,  6],
       [24, 26, 28],
       [ 8, 10, 12]])

In [107]:
arr.__add__(a1)

array([[ 2,  4,  6],
       [24, 26, 28],
       [ 8, 10, 12]])

### Multiplication of Matrix

#### Normal multiplication

In [113]:
np.multiply(a1, arr)

array([[  1,   4,   9],
       [144, 169, 196],
       [ 16,  25,  36]])

#### Dot Product

In [114]:
np.dot(a1, arr)

array([[ 37,  43,  49],
       [224, 263, 302],
       [ 88, 103, 118]])

In [115]:
a1.dot(arr)

array([[ 37,  43,  49],
       [224, 263, 302],
       [ 88, 103, 118]])

### Square Roots

In [116]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081],
       [3.46410162, 3.60555128, 3.74165739],
       [2.        , 2.23606798, 2.44948974]])

### Sum of Elements

In [117]:
np.sum(arr) # sum of every element

60

In [122]:
print(arr)
np.sum(arr, axis=0) # Sum of columns

[[ 1  2  3]
 [12 13 14]
 [ 4  5  6]]


array([17, 20, 23])

In [123]:
np.sum(arr, axis=1) # Sum of rows

array([ 6, 39, 15])

In [124]:
np.sum(arr, axis=2) # Doesn't works as `arr` is a 2x2 matrix

AxisError: axis 2 is out of bounds for array of dimension 2

## Reshaping
### It just re-arranges the array using all the elements

In [126]:
arr.reshape([1,9])

array([[ 1,  2,  3, 12, 13, 14,  4,  5,  6]])

In [127]:
arr.reshape([9,1])

array([[ 1],
       [ 2],
       [ 3],
       [12],
       [13],
       [14],
       [ 4],
       [ 5],
       [ 6]])

In [129]:
arr.reshape([4,1]) #Only possible combinations in 3x3 (9 elements) is [(1,9), (3,3), (9,1)]

ValueError: cannot reshape array of size 9 into shape (4,1)

#### Reshaping to 3D array (just the number of elements in original array matter)

In [133]:
b1 = np.eye(4, dtype=int)
b1

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [173]:
b1.reshape([2,4,2])

array([[[1, 0],
        [0, 0],
        [0, 1],
        [0, 0]],

       [[0, 0],
        [1, 0],
        [0, 0],
        [0, 1]]])

#### Restructuring without using the size of row or column

In [175]:
arr.reshape([-1, 1])

array([[ 1],
       [ 2],
       [ 3],
       [12],
       [13],
       [14],
       [ 4],
       [ 5],
       [ 6]])

In [136]:
arr.reshape([-1,0])

ValueError: cannot reshape array of size 9 into shape (0)

In [177]:
arr.reshape([1, -1])

array([[ 1,  2,  3, 12, 13, 14,  4,  5,  6]])