In [1]:
from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(".././ml_datasets/Iris-f.csv")

In [3]:
si = SimpleImputer(missing_values=np.nan, strategy="mean")

In [4]:
df1 = df.iloc[:,0:4]
si.fit_transform(df1)

array([[5.1       , 3.5       , 1.4       , 0.2       ],
       [4.9       , 3.        , 1.4       , 0.2       ],
       [4.7       , 3.2       , 1.3       , 0.2       ],
       [4.6       , 3.1       , 1.5       , 0.2       ],
       [5.85202703, 3.6       , 1.4       , 0.2       ],
       [5.4       , 3.9       , 1.7       , 0.4       ],
       [4.6       , 3.4       , 1.4       , 0.3       ],
       [5.        , 3.05167785, 3.7738255 , 0.2       ],
       [4.4       , 2.9       , 1.4       , 0.2       ],
       [4.9       , 3.1       , 1.5       , 0.1       ],
       [5.4       , 3.7       , 1.5       , 0.2       ],
       [4.8       , 3.4       , 1.6       , 0.2       ],
       [4.8       , 3.        , 1.4       , 0.1       ],
       [4.3       , 3.        , 1.1       , 0.1       ],
       [5.8       , 4.        , 1.2       , 0.2       ],
       [5.7       , 4.4       , 1.5       , 0.4       ],
       [5.4       , 3.9       , 1.3       , 0.4       ],
       [5.1       , 3.5       ,

In [5]:
si = SimpleImputer(missing_values=np.nan, strategy="most_frequent")
df1 = df.iloc[:,-1:]
si.fit_transform(df1)

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iri

### Feature Scaling of Data

In [6]:
df2 = df.copy(deep=True)
df2.dropna(inplace=True)

In [7]:
# Getting only the columns with numeric values
df2.shape
df3 = df2.iloc[:,:4]
df3.head

<bound method NDFrame.head of      SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
5              5.4           3.9            1.7           0.4
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[146 rows x 4 columns]>

#### MinMaxScaler

In [8]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, Binarizer
mmscaler = MinMaxScaler(feature_range=(0,1))
scaled = mmscaler.fit_transform(df3)

In [9]:
new_df = pd.DataFrame(scaled, columns=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'])

In [10]:
new_df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0       0.222222      0.625000       0.067797      0.041667
1       0.166667      0.416667       0.067797      0.041667
2       0.111111      0.500000       0.050847      0.041667
3       0.083333      0.458333       0.084746      0.041667
4       0.305556      0.791667       0.118644      0.125000

#### StandardScaler

In [11]:
scaler = StandardScaler()
scaled = scaler.fit_transform(df3)
new_df = pd.DataFrame(scaled, columns=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'])

In [12]:
new_df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      -0.918060      1.066468      -1.388712     -1.363428
1      -1.159350     -0.095505      -1.388712     -1.363428
2      -1.400640      0.369284      -1.446100     -1.363428
3      -1.521286      0.136890      -1.331324     -1.363428
4      -0.556124      1.996046      -1.216548     -1.097660

#### Binarizer

In [13]:
bscaler = Binarizer(threshold=5)
scaled = bscaler.fit_transform(df3)
new_df = pd.DataFrame(scaled, columns=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'])

##### Anything above 5 = 1 and below 5 = 0

In [14]:
new_df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              1.0           0.0            0.0           0.0
1              0.0           0.0            0.0           0.0
2              0.0           0.0            0.0           0.0
3              0.0           0.0            0.0           0.0
4              1.0           0.0            0.0           0.0
..             ...           ...            ...           ...
141            1.0           0.0            1.0           0.0
142            1.0           0.0            0.0           0.0
143            1.0           0.0            1.0           0.0
144            1.0           0.0            1.0           0.0
145            1.0           0.0            1.0           0.0

[146 rows x 4 columns]

In [15]:
df4 = df.copy(deep=True)

In [16]:
df4.dropna(axis=0, inplace=True)

In [17]:
df4.shape

(146, 5)

In [18]:
df4.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [19]:
mapping = {'Iris-setosa' : 3, 'Iris-versicolor' : 2, 'Iris-virginica' : 1}
df4.Species = df.Species.map(mapping)
df4.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2      3.0
1            4.9           3.0            1.4           0.2      3.0
2            4.7           3.2            1.3           0.2      3.0
3            4.6           3.1            1.5           0.2      3.0
5            5.4           3.9            1.7           0.4      3.0

## Label Encoder

In [20]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df4.Species = le.fit_transform(df4[['Species']])
df4.tail()

/opt/homebrew/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
145            6.7           3.0            5.2           2.3        0
146            6.3           2.5            5.0           1.9        0
147            6.5           3.0            5.2           2.0        0
148            6.2           3.4            5.4           2.3        0
149            5.9           3.0            5.1           1.8        0

## OneHotEncoder

In [21]:
from sklearn.preprocessing import OneHotEncoder
le=OneHotEncoder()
x = le.fit_transform(df4[['Species']]).toarray()    # creating an array # type: ignore
x

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1

In [22]:
pd.get_dummies(df['Species'])

Iris-setosa  Iris-versicolor  Iris-virginica
0           True            False           False
1           True            False           False
2           True            False           False
3           True            False           False
4           True            False           False
..           ...              ...             ...
145        False            False            True
146        False            False            True
147        False            False            True
148        False            False            True
149        False            False            True

[150 rows x 3 columns]

In [23]:
df.dropna(axis=0, inplace=True)

In [24]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
x = df.iloc[:,:4]
principalComponents = pca.fit_transform(x)

In [25]:
df_new = pd.DataFrame(principalComponents)
df_new

0         1
0   -2.751400  0.356622
1   -2.786004 -0.140028
2   -2.960345 -0.105606
3   -2.818148 -0.280480
4   -2.344267  0.775822
..        ...       ...
141  1.875278  0.186313
142  1.453316 -0.374859
143  1.694765  0.078005
144  1.832162  0.117102
145  1.317822 -0.280077

[146 rows x 2 columns]

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_new['Species'] = le.fit_transform(df[['Species']])

/opt/homebrew/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## Data Pre-proccesing over

In [27]:
df_new

0         1  Species
0   -2.751400  0.356622        0
1   -2.786004 -0.140028        0
2   -2.960345 -0.105606        0
3   -2.818148 -0.280480        0
4   -2.344267  0.775822        0
..        ...       ...      ...
141  1.875278  0.186313        2
142  1.453316 -0.374859        2
143  1.694765  0.078005        2
144  1.832162  0.117102        2
145  1.317822 -0.280077        2

[146 rows x 3 columns]

## Dividing Data for Training and Testing

### Usual distribution (80:20 or 70:30 or 60:40)

## Learning Phase (xtrain, ytrain) = model

In [28]:
x = df_new.iloc[:, :2]
y = df_new['Species']

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, train_size=0.8, shuffle=True, random_state=2)

In [29]:
xtrain.shape, xtest.shape

((116, 2), (30, 2))

In [30]:
xtrain.index, xtest.index

(Index([ 14,  99, 127, 119,  45,  65, 137,  71, 139, 111,
        ...
         47, 141,  95,   7, 104,  75,  43,  22,  72,  15],
       dtype='int64', length=116),
 Index([ 91, 126,   3,  35, 123,  82, 128,  12,  42, 125,   5,  53,  93, 121,
         48,  59,  24,  86,  41,  77,  85, 122,  25,   2, 113,  64, 144,  23,
         44,  54],
       dtype='int64'))

In [31]:
ytrain.value_counts()

Species
2    42
1    39
0    35
Name: count, dtype: int64

In [32]:
ytest.value_counts()

Species
1    11
0    11
2     8
Name: count, dtype: int64

In [33]:
xtrain.value_counts()

0          1        
-2.743925  -0.077647    3
 1.340126  -0.572375    2
-3.298321  -0.469006    1
 1.223635  -0.760783    1
 1.593730   0.242757    1
                       ..
-0.783742  -0.992672    1
-0.983499  -0.733650    1
-2.262304   0.905392    1
-2.275376   0.470619    1
 3.727198   0.235110    1
Name: count, Length: 113, dtype: int64

## Learning

In [34]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(xtrain, ytrain)
reg.coef_, reg.intercept_

(array([ 0.37911737, -0.20680554]), 1.03394390256467)

In [35]:
y_pred = reg.predict(xtest)

## Evaluation Phase (xtest) = (ypredict == ytest)

In [36]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
mean_absolute_error(ytest, y_pred), mean_squared_error(ytest, y_pred)

(0.18755180207842775, 0.06005421220553994)

In [37]:
from sklearn.metrics import r2_score
rscore = r2_score(ytest, y_pred)
print("Accuracy: ", rscore*100, "%")


Accuracy:  90.36563440552835 %


## Plotting of graph

In [38]:
import matplotlib.pyplot as plt